import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "GameHub",
  description: "A modern ui/ux Twitch clone using Next.js 14.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "live stream",
    "trello clone",
    "shadcn",
    "shadcn-ui",
    "radix-ui",
    "cn",
    "clsx",
    "youtube livestream",
    "date-fns",
    "sooner",
    "usehooks-ts",
    "sql",
    "mysql",
    "aiven",
    "prisma",
    "lucide-react",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Sanidhya Kumar Verma",
    url: "https://github.com/sanidhyy",
  },
} as const;
